# -*- coding: utf-8 -*-

{
    'name': 'EBizCharge Payment Acquirer',
    'category': 'Accounting/Payment',
    'summary': 'Payment Acquirer: EBizCharge Implementation',
    'version': '1.0',
    'description': """EBizCharge Payment Acquirer""",
    'depends': ['base', 'payment', 'sale', 'account', 'website_sale', 'stock'],
    'data': [
        'security/ir.model.access.csv',
        'views/payment_ebizcharge_view.xml',
        'views/payment_request_bulk_email.xml',
        'views/ebiz_transaction_views.xml',
        
        'views/payment_views.xml',
        'views/payment_ebizcharge_templates.xml',
        'data/payment_acquirer_data.xml',
        'views/res_config_setting_view.xml',
        
        'views/sale_order_view.xml',
        'views/reporting_logs.xml',
        'views/account_move_view.xml',
        'views/product_template_view.xml',
        'views/res_partner_view.xml',
        'wizard/wizard_process_transaction_views.xml',
        'wizard/wizard_avs_validation_view.xml',
        'wizard/wizard_email_invoice_view.xml',
        'wizard/wizard_email_receipt_view.xml',
        'wizard/message_wizard.xml',
        'wizard/wizard_void_transaction_view.xml',
        'wizard/wizard_request_payment_method_view.xml',
        'schedular/schedule.xml',
        'wizard/wizard_add_new_card_view.xml',
        'wizard/wizard_add_card_validation_view.xml',
        'wizard/wizard_refund_transaction_view.xml',
        'wizard/wizard_download_payment_views.xml',
        'wizard/wizard_show_pending_ebiz_email_view.xml',
        'wizard/wizard_add_new_ach_view.xml',
        'wizard/wizard_multi_sync_resp_view.xml',
        'wizard/wizard_request_email_payment_bulk_view.xml',
        'wizard/wizard_card_expiring_soon_view.xml',
        'wizard/wizard_payment_link_view.xml',
        'views/payment_method_ui_view.xml',
        'views/batch_processing_views.xml',
        'views/sync_download_views.xml',
        'views/transaction_portal.xml',
        'views/upload_customers.xml',
        'views/upload_saleorders.xml',
        'views/upload_products.xml',
        'views/upload_invoice_view.xml',
        'views/upload_credit_notes.xml',
        'views/contact_us.xml',
        'reports/inherited_account_invoice_report_view.xml',
    ],
    'qweb': [
        "static/src/xml/menu.xml",
        "static/src/xml/field_masking.xml",
    ],
    'installable': True,
    # 'post_init_hook': 'create_missing_journal_for_acquirers',
    # 'uninstall_hook': 'uninstall_hook',
    'assets': {
        'web.assets_frontend': [
            'payment_ebizcharge/static/src/scss/portal_payment.scss',
            'payment_ebizcharge/static/src/js/payment_form.js',
            'payment_ebizcharge/static/src/js/manage_form.js',
            'payment_ebizcharge/static/src/js/checkout_form.js',
            'payment_ebizcharge/static/src/js/transaction_history.js',
            'payment_ebizcharge/static/lib/jquery.payment/jquery.payment.js',
            'payment_ebizcharge/static/src/js/payment_portal.js',
        ],
        'web.assets_backend': [
            'payment_ebizcharge/static/src/scss/backend.scss',
            'payment_ebizcharge/static/src/js/make_editable.js',
            'payment_ebizcharge/static/src/js/request_payment_method.js',
            'payment_ebizcharge/static/src/js/upload_customer.js',
            'payment_ebizcharge/static/src/js/upload_salesorder.js',
            'payment_ebizcharge/static/src/js/batch_processing.js',
            'payment_ebizcharge/static/src/js/upload_invoices.js',
            'payment_ebizcharge/static/src/js/upload_products.js',
            'payment_ebizcharge/static/src/js/email_pay_invoices.js',
            'payment_ebizcharge/static/src/js/download_invoice_credit_notes.js',
            'payment_ebizcharge/static/src/js/field_masking.js',
            'payment_ebizcharge/static/src/js/flush_realtime_data.js',
            'payment_ebizcharge/static/src/js/upload_credit_notes.js',
        ]
    }
}
